### ISSUE TITLE
Crash in the editor when using DebugGame Configuration

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#89]
### Environment

How do you use Sentry?
Sentry.Io

Which version of the SDK?
Git 

Which version of Unreal?
Unreal Editor 

### Steps to Reproduce

1. Compile DebugGame Editor 
2. Open a level
3. Play the level 
4. Leave the level
5. Start interacting with the editor

### Expected Result

No crashes

### Actual Result

```
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

UnrealEditor_Sentry_Win64_DebugGame!USentrySubsystem::AddBreadcrumb() [C:\p4ws\ProjectStream_Prototype\Project\Plugins\External\SentryUnrealPlugin\Source\Sentry\Private\SentrySubsystem.cpp:81]
UnrealEditor_Sentry_Win64_DebugGame!USentrySubsystem::AddBreadcrumbWithParams() [C:\p4ws\ProjectStream_Prototype\Project\Plugins\External\SentryUnrealPlugin\Source\Sentry\Private\SentrySubsystem.cpp:94]
UnrealEditor_Sentry_Win64_DebugGame!<lambda_0a11e1e39d2e6b11c1eb6d09c13ead63>::operator()() [C:\p4ws\ProjectStream_Prototype\Project\Plugins\External\SentryUnrealPlugin\Source\Sentry\Private\SentrySubsystem.cpp:266]
UnrealEditor_Sentry_Win64_DebugGame!TBaseFunctorDelegateInstance<void __cdecl(FString const &),FDefaultDelegateUserPolicy,<lambda_0a11e1e39d2e6b11c1eb6d09c13ead63> >::ExecuteIfSafe() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:838]
UnrealEditor_Engine!FUserActivityTracking::SetActivity() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Engine\Private\UserActivityTracking.cpp:23]
UnrealEditor_UnrealEd!FUnrealEdMisc::OnUserActivityTabChanged() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Editor\UnrealEd\Private\UnrealEdMisc.cpp:1289]
UnrealEditor_UnrealEd!FUnrealEdMisc::OnActiveTabChanged() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Editor\UnrealEd\Private\UnrealEdMisc.cpp:1275]
UnrealEditor_UnrealEd!TBaseRawMethodDelegateInstance<0,FUnrealEdMisc,void __cdecl(TSharedPtr<SDockTab,1>,TSharedPtr<SDockTab,1>),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:467]
UnrealEditor_Slate!TMulticastDelegate<void __cdecl(TSharedPtr<SDockTab,1>,TSharedPtr<SDockTab,1>),FDefaultDelegateUserPolicy>::Broadcast() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:967]
UnrealEditor_Slate!FGlobalTabmanager::SetActiveTab() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Slate\Private\Framework\Docking\TabManager.cpp:2470]
UnrealEditor_Slate!SDockingTabStack::OnFocusChanging() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Slate\Private\Framework\Docking\SDockingTabStack.cpp:491]
UnrealEditor_Slate!FSlateApplication::SetUserFocus() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:2805]
UnrealEditor_Slate!FSlateApplication::SetUserFocus() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:2701]
UnrealEditor_Slate!FSlateApplication::RoutePointerDownEvent() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:4890]
UnrealEditor_Slate!FSlateApplication::ProcessMouseButtonDownEvent() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:4779]
UnrealEditor_Slate!FSlateApplication::OnMouseDown() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:4677]
UnrealEditor_ApplicationCore!FWindowsApplication::ProcessDeferredMessage() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2218]
UnrealEditor_ApplicationCore!FWindowsApplication::DeferMessage() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2699]
UnrealEditor_ApplicationCore!FWindowsApplication::ProcessMessage() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:1078]
UnrealEditor_ApplicationCore!FWindowsApplication::AppWndProc() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:916]
user32
user32
InkObj
atlthunk
user32
user32
UnrealEditor_ApplicationCore!FWindowsPlatformApplicationMisc::PumpMessages() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsPlatformApplicationMisc.cpp:138]
UnrealEditor_Win64_DebugGame!FEngineLoop::Tick() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5139]
UnrealEditor_Win64_DebugGame!GuardedMain() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Launch\Private\Launch.cpp:188]
UnrealEditor_Win64_DebugGame!GuardedMainWrapper() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:147]
UnrealEditor_Win64_DebugGame!LaunchWindowsStartup() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:283]
UnrealEditor_Win64_DebugGame!WinMain() [C:\p4ws\ProjectStream_Prototype\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:330]
UnrealEditor_Win64_DebugGame!__scrt_common_main_seh() [d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll
```

**Comment by tustanivsky** [comment]
Hey @Edstub207, I believe this issue has been addressed in PR #88. For now you can disable `Automatically add breadcrumbs` -> `User activity string changed` in plugin settings to avoid crashing the editor

**Comment by Edstub207** [comment]
@tustanivsky Thanks, Sadly that didn't fix it for the member of the team hitting the crash, I'm currently trying to disable Sentry in the editor, but running into issues so not really able to test locally sadly.
